baseURL: https://log.cevtuogrnd.com
# baseURL: https://www.sulvblog.cn  # 绑定的域名
languageCode: zh-cn # en-us
title: CEVTUOLOG
theme: hugo-PaperMod  # 主题名字，和themes文件夹下的一致

enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true

hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics:  # 谷歌统计
# Copyright: Sulv

paginate: 15    # 首页每页显示的文章数

minify:
    disableXML: true
    # minifyOutput: true

permalinks: # 访问博客时网址的显示形式
  post: "/:title/"
  # post: "/:year/:month/:day/:title/"

defaultContentLanguage: en # 最顶部首先展示的语言页面
defaultContentLanguageInSubdir: true

languages:
    en:
      languageName: "English"
      weight: 1
      profileMode:
        enabled: true
        title: CEVTUOLOG---ING
        subtitle: "MADE BY c_jw*"
        imageUrl: "https://cevtuogrnd.com/wp-content/uploads/2021/07/cevuo-logo-small.png"
   #     C:\Users\cjwcj\cevtuolog\content\cevuo-logo-final.png
        imageTitle: 
        imageWidth: 300
        imageHeight: 300
        buttons:
          - name: 📇 clog
            url: posts/clog
         # - name: 👨🏻‍💻 
         #   url: posts/tech
          - name: 🔮 cenvisage
            url: posts/cenvisage
          - name: 🧾 clist
         #   url: posts/clist
      menu:
        main:
          - identifier: search
            name: 🔍 Search
            url: search
            weight: 1
          - identifier: home
            name: 🏠 Home
            url: /
            weight: 2
          - identifier: posts
            name: 📚 Post
            url: posts
            weight: 3
          - identifier: tags
            name: 🧩 Tag
            url: tags
            weight: 15
          - identifier: archives
            name: ⏱ Archive
            url: archives/
            weight: 20
   #       - identifier: about
   #         name: 🙋🏻‍♂️ About
   #         url: about
   #         weight: 50
          - identifier: CEVTUOGNRD
            name: 🌐 CEVTUOGRND
            url: HTTPS://CEVTUOGRND.COM
            weight: 50

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "CEVUOLOG FOR LOG ... ING"
    author: CEVTUO
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto  # defaultTheme: light or  dark 
    disableThemeToggle: false
    DateFormat: "2006-01-02"
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecialistPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    hideFooter: false # 隐藏页脚
    ShowWordCounts: true
    VisitCount: true
    Reward: true #打赏
    ShowLastMod: true #显示文章更新时间

    ShowToc: true # 显示目录
    TocOpen: true # 自动展开目录

    comments: true
    socialIcons:
   #     - name: github
   #       url: "https://github.com/xyming108"
        - name: twitter
          url:  "https://twitter.com/cjwcevtuo"
        - name: facebook
          url: "https://www.facebook.com/chang.jingwei.7"
    #    - name: instagram
    #      url: "img/instagram.png"
    #    - name: QQ
    #      url: "img/qq.png"
        - name: WeChat
          url: "https://cevtuogrnd.com/wp-content/uploads/2021/08/cjw-wecaht-QR-1.jpg"
    #    - name: bilibili
    #      url: "https://space.bilibili.com/234461224"
        - name: email
          url: "mailto:cjw@cevtuogrnd.com"
       
 #       - name: RSS
 #         url: "index.xml"

    label:
        text: "CEVTUOLOG"
       # icon: " "
        iconHeight: 35

    analytics:
        google:
            SiteVerificationTag: ""

    assets:
        favicon: "img/Q.gif"
        favicon16x16: "img/Q.gif"
        favicon32x32: "img/Q.gif"
        apple_touch_icon: "img/Q.gif"
        safari_pinned_tab: "img/Q.gif"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary"]

    twikoo:
      version: 1.5.8

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
    highlight:
        # anchorLineNos: true
        codeFences: true  
        guessSyntax: true
        # lineNos: true
        noClasses: true
        tabWidth: 4
        style: monokai
        # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
        # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
        # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
        # lineNoStart：行号从编号几开始，一般从 1 开始。
        # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
        # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
        # noClasses：使用 class 标签，而不是内嵌的内联样式

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
        